#!/usr/bin/php
<?php
require_once('path.inc');
require_once('get_host_info.inc');
require_once('rabbitMQLib.inc');

$client = new rabbitMQClient("testRabbitMQ.ini","testServer");

$request = array();
$request['type'] = "deck_input";
$request['user'] = (int)$argv[1];
$request['deck_name'] = $argv[2];
$request["card_id_1"] = $argv[3];
$request["card_id_2"] = $argv[4];
$request["card_id_3"] = $argv[5];
$request["card_id_4"] = $argv[6];
$request["card_id_5"] = $argv[7];
$request["card_id_6"] = $argv[8];
$request["card_id_7"] = $argv[9];
$request["card_id_8"] = $argv[10];
$request["card_id_9"] = $argv[11];
$request["card_id_10"] = $argv[12];
$request["card_id_11"] = $argv[13];
$request["card_id_12"] = $argv[14];
$request["card_id_13"] = $argv[15];
$request["card_id_14"] = $argv[16];
$request["card_id_15"] = $argv[17];
$request["card_id_16"] = $argv[18];
$request["card_id_17"] = $argv[19];
$request["card_id_18"] = $argv[20];
$request["card_id_19"] = $argv[21];
$request["card_id_20"] = $argv[22];
$request["card_id_21"] = $argv[23];
$request["card_id_22"] = $argv[24];
$request["card_id_23"] = $argv[25];
$request["card_id_24"] = $argv[26];
$request["card_id_25"] = $argv[27];
$request["card_id_26"] = $argv[28];
$request["card_id_27"] = $argv[29];
$request["card_id_28"] = $argv[30];
$request["card_id_29"] = $argv[31];
$request["card_id_30"] = $argv[32];
$request["card_id_31"] = $argv[33];
$request["card_id_32"] = $argv[34];
$request["card_id_33"] = $argv[35];
$request["card_id_34"] = $argv[36];
$request["card_id_35"] = $argv[37];
$request["card_id_36"] = $argv[38];
$request["card_id_37"] = $argv[39];
$request["card_id_38"] = $argv[40];
$request["card_id_39"] = $argv[41];
$request["card_id_40"] = $argv[42];
$request["card_id_41"] = $argv[43];
$request["card_id_42"] = $argv[44];
$request["card_id_43"] = $argv[45];
$request["card_id_44"] = $argv[46];
$request["card_id_45"] = $argv[47];
$request["card_id_46"] = $argv[48];
$request["card_id_47"] = $argv[49];
$request["card_id_48"] = $argv[50];
$request["card_id_49"] = $argv[51];
$request["card_id_50"] = $argv[52];
$request["card_id_51"] = $argv[53];
$request["card_id_52"] = $argv[54];
$request["card_id_53"] = $argv[55];
$request["card_id_54"] = $argv[56];
$request["card_id_55"] = $argv[57];
$request["card_id_56"] = $argv[58];
$request["card_id_57"] = $argv[59];
$request["card_id_58"] = $argv[60];
$request["card_id_59"] = $argv[61];
$request["card_id_60"] = $argv[62];
$response = $client->send_request($request);
//$response = $client->publish($request);

print_r($response);
